---
title: "Breast Cancer Diagnosis with SVM"
output: html_notebook
---


```{r}
library(caret)
library(e1071)
data<-read.csv("C:\\Users\\damla\\OneDrive\\Belgeler\\GitHub\\R\\PROJE\\SVM\\data.csv")
View(data)
data$id<-NULL
data$X<-NULL
#varNames<-name(data)
#data<-data[,-which(varNames=='X' | varNames=='id')]
str(data)
```



```{r}
names(data)
selectedVars<-c( "diagnosis",              
                 "radius_mean",            
                 "texture_mean",           
                 "perimeter_mean",         
                 "area_mean",              
                 "smoothness_mean",        
                 "compactness_mean",       
                 "concavity_mean",         
                 "concave.points_mean",    
                 "symmetry_mean",          
                 "fractal_dimension_mean")

modeldataselected<-data[,selectedVars]
View(modeldataselected)
```


```{r}
plot(modeldataselected$radius_mean,modeldataselected$texture_mean,pch=19,
     col=c('blue','orange')[as.factor(modeldataselected$diagnosis)])

plot(modeldataselected$area_mean,modeldataselected$perimeter_mean,pch=19,
     col=c('blue','orange')[as.factor(modeldataselected$diagnosis)])

plot(modeldataselected$smoothness_mean,modeldataselected$compactness_mean,pch=19,
     col=c('blue','orange')[as.factor(modeldataselected$diagnosis)])
```



```{r}

modeldataselected$diagnosis<-as.factor(modeldataselected$diagnosis)
set.seed(8)
train<-sample(1:nrow(modeldataselected),size=0.8*nrow(modeldataselected))
trainset<-modeldataselected[train,]
testset<-modeldataselected[-train,]

table(trainset$diagnosis)
table(testset$diagnosis)
head(trainset)

```



```{r}
modellinear<-svm(diagnosis~.,data=trainset,
            kernel='linear')
modelradial<-svm(diagnosis~.,data=trainset,kernel='radial')

modellinear
modelradial

modelradial$coefs
modellinear$coefs
```


```{r}
predictlinear<-predict(modellinear,testset)
predictradial<-predict(modelradial,testset)
confusionlinear<-confusionMatrix(predictlinear,testset$diagnosis)
confusionradial<-confusionMatrix(predictradial,testset$diagnosis)
confusionlinear
confusionradial

```


```{r}
confusionlinear2<-confusionMatrix(predictlinear,testset$diagnosis,positive = 'M')
confusionradial2<-confusionMatrix(predictradial,testset$diagnosis,positive = 'M')

confusionlinear2
confusionradial2
```


```{r}

plot(modellinear,trainset,radius_mean~texture_mean)
plot(modellinear,testset,perimeter_mean~area_mean)


plot(modelradial,trainset,radius_mean~texture_mean)
plot(modelradial,testset,perimeter_mean~area_mean)
```

Gamma defines how far the influence of a single training point reaches.
Small gamma → smoother decision boundary
Large gamma → very flexible boundary that may overfit
C controls how strictly the SVM tries to classify training samples correctly.
Large C → narrower margin, risk of overfitting
Small C → wider margin, risk of underfitting

```{r}

modellineartuning<-tune(svm,diagnosis~.,data=trainset,
                        kernel="linear",
                        ranges=list(cost=2^(-4:2)),
                        tunecontrol=tune.control(cross=5))



modelradialtuning<-tune(svm,diagnosis~.,data=trainset,
                        kernel="radial",
                        ranges=list(gamma=2^(-2:2),cost=2^(-4:2)),
                        tunecontrol=tune.control(cross=5))
```

```{r}
modellineartuning
modelradialtuning
predictlinearcv<-predict(modellineartuning$best.model,testset)
predictradialcv<-predict(modelradialtuning$best.model,testset)
```


```{r}
confusionlinearcv<-confusionMatrix(predictlinearcv,testset$diagnosis)
confusionradialcv<-confusionMatrix(predictradialcv,testset$diagnosis)
confusionlinearcv
confusionradialcv

```